# Automatically label PRs
name: PR labeler
on:
  - pull_request_target
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    if: github.repository == 'tryghost/ghost'
    steps:
      - name: Run labeler
        uses: actions/labeler@ac9175f
