# Run our custom labeler
name: 'Label Issues'

on:
  workflow_dispatch:
  issues:
    types: [opened, closed, labeled]
  pull_request_target:
    types: [closed, labeled]
  schedule:
    - cron: '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'TryGhost'
    timeout-minutes: 1
    steps:
      - name: Run own labeler
        uses: tryghost/actions/actions/label-actions@main
